<h2><b>  Module 2: Data Analytics with Python - Statistics </b></h2>

<h3><b> About Libraries for Statistics </b></h3>

In [1]:
import sys

# run this cell to install numpy
!{sys.executable} -m pip install numpy

# run this cell to install scipy
!{sys.executable} -m pip install scip

distributed 1.21.8 requires msgpack, which is not installed.
You are using pip version 10.0.1, however version 21.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


  Could not find a version that satisfies the requirement scip (from versions: )
No matching distribution found for scip
You are using pip version 10.0.1, however version 21.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [2]:
import sys
import scipy

<h3><b> Objevtive </b></h3>

In [3]:
import numpy as np

# Creating a Basic Array in Numpy
X=np.array([2,5,7,4,4])

<h3><b> Measures of Central Tendency </b></h3>

<h3><b> MEAN </b></h3>

In [4]:
# Mean using Numpy
print("Data",X)
print("Mean:",np.mean(X))

Data [2 5 7 4 4]
Mean: 4.4


<h3><b> MEDIAN </b></h3>

In [5]:
# Finding Median of X
print("Data",X)
print("Median",np.median(X))

Data [2 5 7 4 4]
Median 4.0


<h3><b> MODE </b></h3>

In [6]:
np.unique(X, return_counts=True)

(array([2, 4, 5, 7]), array([1, 2, 1, 1], dtype=int64))

In [7]:
# Finding Mode using numpy
print("Data",X)
val, count = np.unique(X, return_counts=True)
val, count

Data [2 5 7 4 4]


(array([2, 4, 5, 7]), array([1, 2, 1, 1], dtype=int64))

In [8]:
count

array([1, 2, 1, 1], dtype=int64)

In [9]:
# Finding Mode using Scipy

from scipy import stats

print("Mode scipy:",stats.mode(X))
modus = stats.mode(X)

Mode scipy: ModeResult(mode=array([4]), count=array([2]))


In [10]:
modus

ModeResult(mode=array([4]), count=array([2]))

<h3><b> Measures of Spread </b></h3>

In [ ]:
Spread can be measured in-

Range
Quartiles and Interquartile range
Percentile
Variance
Standard deviation

<h3><b> RANGE </b></h3>

In [11]:
# Calculating the Range
print("Data ",X)
print("Range ",X.max()-X.min())

Data  [2 5 7 4 4]
Range  5


<h3><b> QUARTILES AND IQR(Interquartile Range) </b></h3>

In [12]:
# Defining Data
data1=np.array([5, 3, 4, 8, 5, 8, 7, 11])
print("Data",data1)

# First quartile (Q1)
Q1 = np.quantile(data1, .25, interpolation = 'midpoint')
print("\nQuartile 1:",Q1)
 
# Second quartile (Q2)
Q2 = np.quantile(data1, .50, interpolation = 'midpoint')
print("Quartile 2:",Q2)

# Third quartile (Q3)
Q3 = np.quantile(data1, .75, interpolation = 'midpoint')
print("Quartile 3:",Q3)

# Interquaritle range (IQR)
IQR = Q3 - Q1
print("\nInterquartile Range",IQR)

Data [ 5  3  4  8  5  8  7 11]

Quartile 1: 4.5
Quartile 2: 6.0
Quartile 3: 8.0

Interquartile Range 3.5


<h3><b> PERCENTILES </b></h3>

In [13]:
print("Data",data1)
percentile_20 = np.percentile(data1,20)
print("20th Percentile:",round(percentile_20,2))

Data [ 5  3  4  8  5  8  7 11]
20th Percentile: 4.4


<h3><b> VARIANCE AND STANDARD DEVIATION </b></h3>

In [14]:
import numpy as np

data1=np.array([1, 3, 4, 5, 5, 6, 7, 11])

print("Data",data1)

'''
    "Delta Degrees of Freedom": the divisor used in the calculation is
    ``N - ddof``, where ``N`` represents the number of elements. By
    default `ddof` is zero.
'''
print("Varaince:",np.var(data1,ddof=1))
print("Standard Deviation:",np.std(data1,ddof=0)) # populasi
print("Standard Deviation:",np.std(data1,ddof=1)) # sampel

Data [ 1  3  4  5  5  6  7 11]
Varaince: 8.785714285714286
Standard Deviation: 2.7726341266023544
Standard Deviation: 2.9640705601780613


In [15]:
import numpy as np
import statistics

E = [60,70,70,70,80,80,80,80,90,100]
F = [75,75,75,75,80,80,80,80,80,80]

# mean
print("Nilai Mean E : ", np.mean(E))

# range
print("Nilai Range E :", np.max(E) - np.min(E))

# varians
print("Nilai Varians E :", np.var(E))

# Standart Deviasi
print("Nilai Standart Deviasi E: ", np.std(E)) # std populasi
print("Nilai Standart Deviasi E: ", statistics.stdev(E)) # std sampel, bisa pakai pst.dev untuk populasi

Nilai Mean E :  78.0
Nilai Range E : 40
Nilai Varians E : 116.0
Nilai Standart Deviasi E:  10.770329614269007
Nilai Standart Deviasi E:  11.352924243950934


<h3><b> COVARIANCE AND CORRELATION </b></h3>

In [16]:
x = np.array([1,2,3,4,5,6,7,8,9])
print(x)
y = np.array([9,8,7,6,5,4,3,2,1])
print(y)

print("\nCovariance ",np.cov(x,y)[0,1])

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]

Covariance  -7.5


<h3><b> CORRELATION </b></h3>

In [17]:
# Return a correlation coefficient matrix
print(np.corrcoef(x,y))

[[ 1. -1.]
 [-1.  1.]]


<h3><b> KURTOSIS </b></h3>

In [18]:
data2=np.linspace(-10,10,100)
print("Kurtosis",stats.kurtosis(data2))

Kurtosis -1.2002400240024003


In [19]:
data2

array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72

<h3><b> SKEWNESS </b></h3>

In [20]:
from IPython.display import HTML
from IPython.display import display

# Taken from https://stackoverflow.com/questions/31517194/how-to-hide-one-specific-cell-input-or-output-in-ipython-notebook
tag = HTML('''<script>
code_show=true; 
function code_toggle() {
    if (code_show){
        $('div.cell.code_cell.rendered.selected div.input').hide();
    } else {
        $('div.cell.code_cell.rendered.selected div.input').show();
    }
    code_show = !code_show
} 
$( document ).ready(code_toggle);
</script>
To show/hide this cell's raw code input, click <a href="javascript:code_toggle()">here</a>.''')
display(tag)



from scipy.stats import skewnorm
import matplotlib.pyplot as plt

numValues = 10000
maxValue = 100
skewness = -5   #Negative values are left skewed, positive values are right skewed.

random = skewnorm.rvs(a = skewness,loc=maxValue, size=numValues)  #Skewnorm function

random = random - min(random)      #Shift the set so the minimum value is equal to zero.
random = random / max(random)      #Standadize all the vlues between 0 and 1. 
random = random * maxValue         #Multiply the standardized values by the maximum value.

#Plot histogram to check skewness
plt.hist(random,30,density=True, color = 'red', alpha=0.1)
plt.show()


<Figure size 640x480 with 1 Axes>

In [21]:
print("Skewness",stats.skew(data2))

Skewness -2.8663736585314984e-17


<h3><b> Eigen VectorS </b></h3>

In [22]:
import numpy as np
x = np.matrix([[5,6,0],[3,7,5],[5,6,1]])
x

matrix([[5, 6, 0],
        [3, 7, 5],
        [5, 6, 1]])

In [23]:
e = np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
# creating a new matrix which  is linear transformation of x
m = x + 45*e
np.linalg.eig(x)

(array([13.173862+0.j        , -0.086931+1.13264162j,
        -0.086931-1.13264162j]),
 matrix([[ 0.49832574+0.j        ,  0.66254382+0.j        ,
           0.66254382-0.j        ],
         [ 0.6788743 +0.j        , -0.56171911+0.12507078j,
          -0.56171911-0.12507078j],
         [ 0.53925981+0.j        ,  0.37031456-0.30451889j,
           0.37031456+0.30451889j]]))

In [25]:
np.linalg.eig(m)

(array([58.173862+0.j        , 44.913069+1.13264162j,
        44.913069-1.13264162j]),
 matrix([[ 0.49832574+0.j        ,  0.66254382+0.j        ,
           0.66254382-0.j        ],
         [ 0.6788743 +0.j        , -0.56171911+0.12507078j,
          -0.56171911-0.12507078j],
         [ 0.53925981+0.j        ,  0.37031456-0.30451889j,
           0.37031456+0.30451889j]]))