<h2><b>Latihan-4 (Operasi Matriks)</b></h2>

In [2]:
import numpy as np

In [3]:
A = np.array([[1,2],[7,8]])
B = np.array([[3,5],[1,6]])

In [21]:
print("hasil perhitungan 2*A = \n", 2*A)

hasil perhitungan 2*A = 
 [[ 2  4]
 [14 16]]


In [22]:
print("hasil perhitungan 2+A = \n", 2+A)

hasil perhitungan 2+A = 
 [[ 3  4]
 [ 9 10]]


In [23]:
print("hasil perhitungan A+B = \n", A+B)

hasil perhitungan A+B = 
 [[ 4  7]
 [ 8 14]]


In [24]:
print("hasil perhitungan A-B = \n", A-B)

hasil perhitungan A-B = 
 [[-2 -3]
 [ 6  2]]


In [25]:
print('determinan matriks A = ', np.linalg.det(A))

determinan matriks A =  -6.0


In [29]:
D = np.linalg.inv(B)
print('invers matriks A = \n', D)

invers matriks A = 
 [[ 0.46153846 -0.38461538]
 [-0.07692308  0.23076923]]


In [30]:
trans = D.transpose()
print('Transpose matriks D = \n', trans)

Transpose matriks D = 
 [[ 0.46153846 -0.07692308]
 [-0.38461538  0.23076923]]


In [31]:
eigen_nilai_A, eigen_vektor_A = np.linalg.eig(A)

In [32]:
print('Nilai Eigen Matriks A = \n', eigen_nilai_A)

Nilai Eigen Matriks A = 
 [-0.62347538  9.62347538]


In [33]:
print('Eigen Vektor Matriks A = \n', eigen_vektor_A)

Eigen Vektor Matriks A = 
 [[-0.77640358 -0.22592838]
 [ 0.63023605 -0.97414391]]


In [34]:
eigen_nilai_B, eigen_vektor_B = np.linalg.eig(B)

In [35]:
print('Nilai Eigen Matriks B = \n', eigen_nilai_B)

Nilai Eigen Matriks B = 
 [1.8074176 7.1925824]


In [36]:

print('Eigen Vektor Matriks B = \n', eigen_vektor_B)

Eigen Vektor Matriks B = 
 [[-0.97271381 -0.76626443]
 [ 0.23200828 -0.64252535]]


In [37]:
print("Matriks B = \n", B)

Matriks B = 
 [[3 5]
 [1 6]]


In [38]:
print("Matriks D = \n", D)

Matriks D = 
 [[ 0.46153846 -0.38461538]
 [-0.07692308  0.23076923]]


In [39]:
#perkalian antar entry B*D
print("Hasil perhitungan antar entry B*D = \n", B*D)

Hasil perhitungan antar entry B*D = 
 [[ 1.38461538 -1.92307692]
 [-0.07692308  1.38461538]]


In [40]:
#perkalian matriks B dan D
print("Hasil perhitungan perkalian matriks B*D = \n", np.matmul(B,D))

Hasil perhitungan perkalian matriks B*D = 
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
