In [1]:
import numpy as np
import numpy.linalg as nlin

A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])

A,B

(array([[1, 2],
        [7, 8]]),
 array([[3, 5],
        [1, 6]]))

In [2]:
2*A

array([[ 2,  4],
       [14, 16]])

In [3]:
2+A

array([[ 3,  4],
       [ 9, 10]])

In [4]:
A+B

array([[ 4,  7],
       [ 8, 14]])

In [5]:
A-B

array([[-2, -3],
       [ 6,  2]])

In [6]:
nlin.det(A)

-6.0

In [7]:
D = nlin.inv(B)

D

array([[ 0.46153846, -0.38461538],
       [-0.07692308,  0.23076923]])

In [8]:
np.transpose(D)

array([[ 0.46153846, -0.07692308],
       [-0.38461538,  0.23076923]])

In [9]:
nilaiEigA, vektorEigA=nlin.eig(A)

print("Nilai Eig matrix A :\n",nilaiEigA)
print("\nVektor Eig matrix A :\n", vektorEigA)

Nilai Eig matrix A :
 [-0.62347538  9.62347538]

Vektor Eig matrix A :
 [[-0.77640358 -0.22592838]
 [ 0.63023605 -0.97414391]]


In [10]:
nilaiEigB, vektorEigB=nlin.eig(B)

print("Nilai Eig matrix B :\n",nilaiEigB)
print("\nVektor Eig matrix B :\n", vektorEigB)

Nilai Eig matrix B :
 [1.8074176 7.1925824]

Vektor Eig matrix B :
 [[-0.97271381 -0.76626443]
 [ 0.23200828 -0.64252535]]
